//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IDProduct { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Stock { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
