//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int IDSeller { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Cellphone { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
